/**
 * Starter content. Everything marked PLACEHOLDER must be replaced in Admin before launch.
 * Policy texts are drafts for the client's legal/DPO review, not legal advice.
 */

export const PLACEHOLDER = "[PLACEHOLDER]";

export const aboutPage = `
## Our mission

${PLACEHOLDER} Praxis Center for Advanced Management exists to close the gap between management theory and day-to-day practice. We run short, intensive programs taught by scholar-practitioners — faculty who hold doctorate degrees *and* have led real projects, teams and organizations.

## The scholar-practitioner model

- **Doctorate-level faculty.** Every lead facilitator holds a doctorate and brings research-grounded frameworks.
- **Practice first.** Sessions are built around workshops, case clinics and tools you apply at work the following Monday.
- **Small cohorts.** We cap each batch so every participant gets feedback from faculty.

## Our founders' story

${PLACEHOLDER} Replace this section with the founders' story: why Praxis was started, the founders' backgrounds, and what they want every participant to walk away with.

## Registration

Praxis Center for Advanced Management is registered with the Securities and Exchange Commission (SEC) of the Philippines.
`.trim();

export const privacyPage = `
> **Draft for review.** This privacy notice is a starting template aligned with the Data Privacy Act of 2012 (RA 10173). Have it reviewed by your Data Protection Officer or counsel before launch.

**Effective date:** ${PLACEHOLDER}

Praxis Center for Advanced Management ("Praxis", "we") respects your privacy. This notice explains how we collect, use, store and protect personal data when you visit praxiscenter.ph, register for a program, or contact us.

## What we collect

- **Registration and billing details:** name, email, mobile number, job title, organization, billing name and address, and (optionally) your company's TIN.
- **Attendee details:** information about each person you register, including dietary or accessibility needs you choose to share.
- **Payment records:** payment channel used, reference numbers and proof-of-payment images you upload. We do not store card or e-wallet credentials.
- **Communications:** messages you send through our contact and inquiry forms.
- **Website usage:** cookies and similar technologies. Analytics and marketing cookies are used only if you consent.

## Why we use it (purposes and lawful basis)

- To process registrations, confirm seats, and deliver training (contract).
- To issue order acknowledgments and comply with tax and accounting requirements (legal obligation).
- To send schedule updates, reminders and certificates (contract / legitimate interest).
- To send newsletters and program announcements — **only with your separate consent**, which you may withdraw at any time.
- To improve our website and programs (legitimate interest, or consent for analytics cookies).

## Sharing

We share data only with service providers who help us operate — for example hosting, email delivery and payment processing — under agreements that require them to protect it, or when required by law. We do not sell personal data.

## Retention

We keep registration and payment records for as long as needed for the purposes above and as required by law (e.g. tax record-keeping periods), then securely delete or anonymize them.

## Your rights

Under RA 10173 you have the right to be informed, to access, to object, to erasure or blocking, to rectification, to data portability, to file a complaint with the National Privacy Commission, and to damages. To exercise these rights, contact our Data Protection Officer below.

## Data Protection Officer

${PLACEHOLDER} The DPO's name and email are set in Admin → Settings and shown on this page.

## Security

We use encryption in transit, access controls, and restricted admin access to protect your data.
`.trim();

export const termsPage = `
> **Draft for review.** Replace or adapt these terms with counsel before launch.

## Registration and seats

A seat is reserved when you place an order and is held for a limited period while we await payment. Seats are confirmed once payment is verified. Unpaid orders are released automatically after the hold period.

## Pricing

Prices are in Philippine pesos (₱). Praxis Center is a non-VAT registered entity. Early-bird pricing applies to orders placed on or before the early-bird deadline. Group rates apply to orders with the minimum number of seats for the same batch.

## Payments

We accept payments through the channels listed at checkout (e.g. GCash, QR Ph, bank transfer). Please upload your proof of payment on your order page so we can verify it promptly. Documents generated by this website are order acknowledgments and are not BIR official receipts.

## Changes to programs

We may change schedules, venues or faculty when necessary. If we cancel a batch, you may transfer to another batch or receive a full refund.

## Refunds, cancellations and transfers

See our Refund & Transfer Policy.

## Conduct and intellectual property

Course materials are for the personal use of registered participants and may not be reproduced or distributed without permission.
`.trim();

export const refundPage = `
> **Draft for review.** ${PLACEHOLDER} Confirm the exact windows and fees with management before launch.

## Cancellations by the participant

- **14 or more days before the start date:** full refund less bank/e-wallet charges, or free transfer to another batch.
- **7–13 days before:** 50% refund, or free transfer to another batch.
- **Less than 7 days before / no-show:** no refund; you may send a substitute from the same organization at no extra cost.

## Substitutions

You may substitute another participant at any time before the program starts. Update attendee details on your order page or email us.

## Transfers

Transfers to a future batch of the same program are allowed once, subject to seat availability.

## Cancellations by Praxis

If we cancel a batch, you may choose a full refund or a transfer to another batch.

## How to request

Email us with your order number. Refunds are processed within ${PLACEHOLDER} business days through the original payment channel where possible.
`.trim();

export const courseDescription = `
${PLACEHOLDER} **Practical Project Management** is an intensive, four-Saturday program for professionals who manage projects — whether or not "project manager" is in their title.

You will learn a practical, standards-aligned approach to planning, executing and closing projects, and apply it to a real project from your own workplace. Every session combines short, research-grounded input from doctorate-level faculty with hands-on workshops, templates and peer clinics.

By the final Saturday you will have a complete project plan — charter, work breakdown structure, schedule, budget, risk register and stakeholder plan — ready to use at work.
`.trim();

export const courseOutline = `
### Day 1 — Foundations and project initiation *(in person, BGC)*
- Projects, programs and operations: what makes projects different
- Predictive, agile and hybrid approaches: choosing the right fit
- Writing a project charter and business case
- Stakeholder identification and analysis

### Day 2 — Planning scope, schedule and cost *(online, Zoom)*
- Requirements and scope statements
- Work breakdown structures
- Scheduling, dependencies and the critical path
- Estimating and building a budget

### Day 3 — Risk, quality, people and communication *(online, Zoom)*
- Risk identification, analysis and response planning
- Quality planning and control
- Leading project teams and managing conflict
- Communication and reporting plans

### Day 4 — Execution, control and closing *(in person, BGC)*
- Monitoring progress and earned value basics
- Change control and issue management
- Closing projects and capturing lessons learned
- **Capstone:** present your project plan for faculty feedback
`.trim();

export const facultyBioA = `
${PLACEHOLDER} Dr. Faculty One is a scholar-practitioner with more than 15 years of experience leading infrastructure and technology projects in the public and private sectors. They hold a Doctor of Business Administration and teach graduate courses in project and operations management.

Replace this bio, photo and credentials in Admin → Faculty.
`.trim();

export const facultyBioB = `
${PLACEHOLDER} Dr. Faculty Two specializes in organizational change and team leadership. They hold a PhD in Management and have advised organizations on transformation programs across banking, BPO and government.

Replace this bio, photo and credentials in Admin → Faculty.
`.trim();

export const faqs: { question: string; answer: string; category: string; sortOrder: number }[] = [
  {
    category: "Registration",
    sortOrder: 1,
    question: "How do I register?",
    answer:
      "Choose a batch, add seats to your cart, enter each attendee's details, and select a payment option. Your seats are held for 5 days while we wait for your payment.",
  },
  {
    category: "Registration",
    sortOrder: 2,
    question: "Can my company register several employees?",
    answer:
      "Yes. Add multiple seats in one order and enter each attendee's details. Orders with 3 or more seats for the same batch get our group rate. You may also choose **Bill my company** to receive a proforma invoice.",
  },
  {
    category: "Payments",
    sortOrder: 3,
    question: "What payment methods do you accept?",
    answer:
      "GCash, QR Ph (scan with most banking and e-wallet apps), and BPI bank transfer. After paying, upload your proof of payment on your order page and we will confirm your seat.",
  },
  {
    category: "Payments",
    sortOrder: 4,
    question: "How does early-bird pricing work?",
    answer:
      "Orders placed on or before the early-bird deadline get the early-bird rate — even if payment is completed after the deadline, as long as it is within the 5-day hold period.",
  },
  {
    category: "Payments",
    sortOrder: 5,
    question: "Do you issue official receipts?",
    answer:
      "We email an order acknowledgment when you register. Please contact us if your company needs a BIR official receipt or invoice for your payment.",
  },
  {
    category: "Programs",
    sortOrder: 6,
    question: "What does hybrid mean for this program?",
    answer:
      "Some sessions are held in person at our venue in BGC, Taguig, and others live online via Zoom. The schedule on each program page shows which days are which.",
  },
  {
    category: "Programs",
    sortOrder: 7,
    question: "Will I receive a certificate?",
    answer:
      "Yes. Participants who complete the program receive a certificate of completion with a unique verification code.",
  },
];
